'use strict';
const D=window.COURSE;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
D.schedule.forEach((s,i)=>{const li=el('li');li.append(el('span',String(i+1).padStart(2,'0'),'time'),el('h3',s.name),el('p',s.description));document.querySelector('#timeline').append(li);});
D.videos.slice(0,2).forEach((v,i)=>{const row=el('article',null,'video'),info=el('div'),player=el('div',null,'video-preview');info.append(el('p',`${String.fromCharCode(65+i)}　${v.publisher}　${v.date}`,'video-meta'),el('h3',v.title),el('p',v.purpose),el('p','播放前：'+v.before),el('p','播放後：'+v.after));const a=el('a','開啟原發布影片');a.href=v.watch;a.target='_blank';a.rel='noopener noreferrer';info.append(a);player.append(el('p','點選後連線至 YouTube。也可使用左側原影片連結。'));const b=el('button','載入建議片段');b.type='button';b.addEventListener('click',()=>{const f=el('iframe');f.title=v.title;f.src=`https://www.youtube-nocookie.com/embed/${v.id}?start=${v.start}&end=${v.end}&rel=0`;f.allow='encrypted-media; picture-in-picture';f.allowFullscreen=true;f.referrerPolicy='strict-origin-when-cross-origin';player.replaceChildren(f,el('small','若播放器受限制，請改用原影片連結。'));});player.append(b);row.append(info,player);document.querySelector('#video-list').append(row);});
D.scenarios.forEach(s=>{const a=el('article',null,'scenario');a.append(el('h3',s.name),el('p',s.text));const d=el('details');d.append(el('summary','討論後查看回饋'),el('p',s.answer));a.append(d);document.querySelector('#scenario-list').append(a);});
D.quiz.forEach((q,i)=>{const f=el('fieldset');f.append(el('legend',`${i+1}. ${q.q}`));q.options.forEach((o,j)=>{const l=el('label'),inp=el('input');inp.type='radio';inp.name='q'+i;inp.value=String(j);l.append(inp,document.createTextNode(o));f.append(l);});const feedback=el('div',null,'feedback');feedback.id='fb'+i;f.append(feedback);document.querySelector('#quiz-form').append(f);});
document.querySelector('#quiz-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const missing=D.quiz.findIndex((_,i)=>!data.has('q'+i));if(missing>=0){document.querySelector('#result').textContent=`請先完成第 ${missing+1} 題。`;document.querySelector(`[name="q${missing}"]`).focus();return;}let score=0;D.quiz.forEach((q,i)=>{const correct=Number(data.get('q'+i))===q.a;if(correct)score++;document.querySelector('#fb'+i).textContent=(correct?'答對。':'再想一想。正確答案：'+q.options[q.a]+'。')+q.why;});document.querySelector('#result').textContent=`你答對 ${score} / 5 題。${score>=4?'已達本課基本檢核標準。':'請依回饋複習後再試。'} 今天放學，你要把哪一個行動做出來？`;});
document.querySelector('#reset-quiz').addEventListener('click',()=>{document.querySelector('#quiz-form').reset();document.querySelectorAll('.feedback').forEach(e=>e.textContent='');document.querySelector('#result').textContent='';document.querySelector('[name="q0"]').focus();});
D.sources.forEach(s=>{const l=el('li'),a=el('a',s[0]);a.href=s[1];a.target='_blank';a.rel='noopener noreferrer';l.append(a);document.querySelector('#source-list').append(l);});

D.local_sources.forEach(s=>{const li=el('li');li.append(el('strong',s.file),el('span','原文位置：'+s.section),el('p',s.use));document.querySelector('#local-source-list').append(li);});
